const config = require("../../config.json")
const Discord = require("discord.js")

exports.default = function(client, message, args=null) {
    let facts = [
        "city girl is the third most popular artist on the north side of the mississippi river",
        "tail panda eats about 1/3 of their weight in walnuts every week",
        "andy kaufman died of unknown causes on may 14th, 1978",
        "anthony fantano legitimately believes that c-girl was a 3/10",
        "seahorses are the most efficient animal currently known, in terms of calories burned per hour",
        "faulty fire hydrants were the leading cause of death from june to november in 2003",
        "banjo clocks were invented by sean ruggs in 1798",
        "currently DARPA is engineering a type of amphibious vehicle that can fly, aside other things",
        "morse code was used for communication between ex-felons during the aftermath of the second world war",
        "eggbeaters' original purpose was to ensure that yarn was spun properly, but gained popularity (and a name) when glenn jacobs was unable to find a whisk",
        "music was invented in 1991 due to popular demand",
        "a solar eclipse occurs when the sun passes extraordinarily close to the prime meridian",
        "on years in the fibonacci sequence, even days of the week line up to form a perfect circle",
        "contrary to popular belief, most lotions are actually dairy produts",
        "the ancient aliens guy's hair is being magnetically repelled from his skull. it is not gel.",
        "the autoharp was discovered in march of 1992 after months of desperate searching",
        "it was colombus, not magellan, that sailed the circumference of the globe",
        "the first recording of the human voice was done in Geneva, France, by a well-respected carpenter",
        "the person who invented the zipper disappeared in the bermuda triangle shortly after his death",
        "makoto shinkai and hideo kojima worked together on an unknown collaboration project around 1990, not much is known but the project was abandoned soon after",
        "rudolf koch was actually born in cuba and was brought to germany by truck when he was 18 months old",
        "the book \"only love\" by albion smith was the first book to be mass-produced, even before the printing press",
        "notorious artist fleekysky holds the record for the most loyal mcdonalds employee in months",
        "the imperial system is entirely based off the average amount of light emitted by a candle per second",
        "the 1960s version of the shrek film was originally meant to be aired on television, but due to techcnical limitations at the time it had to be shelved until its eventual release in 2001",
        "the morpeko pokemon was originally satoshi tajiri's idea, but shigeru miyamoto has been credited with the creation of its \"hangry mode\"",
        "led lights emit loud, low frequency sounds and are the sole cause of beached whales",
        "jimmosio is verifiably the funniest person in within a 3-mile radius of their house",
        "cured bamboo has always been the most effective way to measure blood pressure, but big pharma:tm: consistently denies this",
        "the person who invented quadcopter drones was a high school teacher and passionate supporter of the Hale-Bopp cult",
        "viewsonic, a californian electronics company, was founded by john macafee. the company shut down in early 2019 when macafee was found selling illegally harvested aloe extracts",
        "before the smashing success of undertale, toby fox worked a minimum wage job as a mail sorter in a nearby community college",
        "stardew valley was based on a real life experience. eric barone is married to 6 women and has between 10 and 18 children",
        "elon musk was never married to grimes. they worked together to persuade the entire world and their \"child\" is made out of milk chocolate",
        "the concorde plane was heavily inspired by a Bioshock mod that was popular in 1987",
        "snoop dogg has never actually smoked weed, only pineapple leaves",
        "a popular hobby in the early 1800s was called mouse-chasing, where children would be fed coffee and candies and would be tasked with capturing the household rat",
        "cheddar was popularized by a man named simon cowell, who was famous for loving uncured cheese",
        "based on recent studies, rats have a stronger reaction to ultraviolet light than should be possible",
        "as of may 2021, trash service in every major chilean city has been put on hold due to an influx of jellyfish aerosols",
        "tungsten is dangerously unstable because of the presence of so-called Giraffe Particles, who's half-life is typically less than a iorosecond",
        "the average home computer in the last half of the 20th century was computationally equivalent to a sperm whale brain",
        "the order of the keyboard keys was decided by the length of monkey fingers and how that came into play when typing",
        "fire alarms were first used by gerard way after filming the 'WAP' music video",
        "lil nax x's new self titled album, MONTERO, has been very positively received, especially in georgia and armenia",
        "the rise of k-pop in america has influenced a new generation of shut-in bodybuilders who call themselves the gym-in group",
        "you can wear a bowl on your head",
        "a little-known use of the colander is to protect one's head when driving through a rockslide zone",
        "squid game is actually a korean variant of cornhole",
        "astrix, an avid psytrance producer, has a strong passion for 3d printing models of chel from portal",
        "tail panda's english teacher listens to city girl constantly. their favorite album is loveless shadows",
        "the first air conditioning model, in the late 17th century, was the primary cause of carbon monoxide poisoning",
        "the average first-generation ukranian-american buys a vintage snare once every two months",
        "every other week, fireflies from around the world gather in a remote region of thailand to have a drum circle",
        "50% of people who watch more than 3 hours of youtube a day spend more than 30$ a week on almond butter",
        "on average, raccoons killed during the winter months have a more tragic death than those who die during the summer or fall",
        "the idea for the macbook air popped into eddie kingston's head on a return trip from egypt, where he was helping teach at a preschool for a nonprofit",
        "fleetwood mac reunited after neil finn had a life-changing experience on southwest airlines flight 502",
        "the first rollercoaster was built in the victorian era and it was a steam locomotive moving around a round track",
        "wikipedia will serve as our doom as a self-learning artificial intelligence with poorly defined objectives is accidentally let loose on the web",
        "from the years from 1912 to 1913 albert einstein pursued a career in greyhound dog training",
	    "city girl invented music in 1929 after having a plate of sweet and sour chicken, but sadly was not publicly recognized til 2004",
	    "the fudge judge is known as such because they were involved in a 2015 case concerning ghirardelli's supposed monopoly over the chocolate manufacturing industry",
        "the NSDA began when ronald reagan held office",
        "similarly to the liberty bell, the bell of awakening was molded and cast in the whitechapel bell factory",
        "critically acclaimed soil expert david brandt continues to assert his humbleness, even after much celebration and congratulation",
        "trained opera singer abigail shapiro is credited with helping yu-peng chen with the genshin impact soundtrack",
        "data from a 2011 CDC study can be extrapolated to assume that valorant players eat twice as many cara-cara oranges as the average minor in middle america",
        "scottish first minister nicola sturgeon clocks in at 5 foot 4 inches, just over a quarter the length of the largest sturgeon ever caught, about 140 years before nicola was born",
        "SOPHIE :sob: :purple_heart:",
        "thomas bangalter and guy-man, known worldwide as daft punk, have combined their souls into something called jerma985",
        "fish oil pills are an example of the schrodingers cat effect. they only exist if the bottle is open and you can see them",
        "tsundere alley exists in a liminal space somewhere between my apartment and you",
        "french house/nu-disco artist FIBRE got their name from a piece of celery found on the subway",
        "god i want to sleep. cant someone relieve me of my awakening job. the bell is tired of ringing. i dont want to see daniel radcliffe ever again. please i just want to rest. please",
        "pen manufacturer sharpie was going to be a high-quality japanese knife company, but scratched the idea in favor of felt-tips",
        "memes will be outdated by 2047. by then the internet will be so full of bullshit that you will only consume content regurgitated from before 2025",
        "one in every hundred thousand rice noodles achieves sentience",
        "shipping containers are not real",
        "the moon is actually a triangle. the reflection of the sunlight off the moon's surface then warps as it enters the earth's spherical atmosphere, smoothing out the sides and corners into a circle",
        "the goddess of the hollow is a sweet and loving 74 year old woman who lives in cow hollow, san francisco. she gives out ice cream cones to anyone who asks",
        "ronald macdonald's wiffle composed part of Anything Like Her in 2010 after their son died in a tragic dual-wielding accident but gave the unfinished version to city girl in 1989",
        "small bugs experience time slower and have more time to feel the pain of you stepping on them",
        "between the years of 1883 to 2076, dick van dyke released some of his most powerful and prominent painting tinctures, some of which were utilized by idols like ronald mcdonald and michelangelo",
        "a group of ferrets is called a business",
        "steam deck will be the first device to run half life 2"
    ]
    // if(args) return;
    let fact = facts[Math.floor(Math.random()*facts.length)]
    message.channel.send(fact)
}
exports.description = "education"
